### ISSUE TITLE
Thank you very much for the program!

### ISSUE THREAD

**Issue by mrkaban** [cfgnunes/wxmp3gain#10]
Hello, thank you very much for a good program under a free open source license! Added a program to a Russian-language site about free software, here is the [link](https://xn--90abhbolvbbfgb9aje4m.xn--p1ai/%D0%BC%D1%83%D0%BB%D1%8C%D1%82%D0%B8%D0%BC%D0%B5%D0%B4%D0%B8%D0%B0/%D0%BF%D1%80%D0%BE%D1%87%D0%B5%D0%B5/wxmp3gain-%D0%BD%D0%BE%D1%80%D0%BC%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D1%8F-%D0%B3%D1%80%D0%BE%D0%BC%D0%BA%D0%BE%D1%81%D1%82%D0%B8-mp3.html).

The project is interesting, so please don't abandon it!

**Comment by cfgnunes** [comment]
Hello, @mrkaban !

Apologies for the delay; life has been quite busy lately.

I deeply appreciate your kind words and for sharing the program on the Russian-language site! It's incredibly uplifting to witness such support and enthusiasm for open-source projects. Your encouragement truly means a lot to me.

Thank you, once more, for your support.
Warm regards,
