### ISSUE TITLE
How to add aacgain support in Windows?

### ISSUE THREAD

**Issue by bremaya** [cfgnunes/wxmp3gain#19]
In Mp3gain for Windows we have the option to add supoort for aac gain and in wxMp3gain (Windows) how I get this?

**Comment by bremaya** [comment]
?

**Comment by cfgnunes** [comment]
Oi, Breno!
Espero que esteja tudo bem contigo.

Gostaria de compartilhar algo importante: devido a uma série de compromissos, não conseguirei dedicar o tempo necessário para continuar o desenvolvimento ou fornecer o suporte ao projeto. Além disso, pessoalmente, tenho utilizado cada vez mais serviços de streaming para ouvir músicas, o que me afastou de utilizar arquivos de áudio locais (MP3, AAC, etc.).

Diante dessas circunstâncias, tomei decisão de encerrar e arquivar o projeto. Mesmo desejando fazer isso de maneira organizada, encontrar tempo para essa tarefa tem sido desafiador.

Manter um projeto ativo exige não apenas tempo, mas também motivação contínua, algo que, infelizmente, tem se dissipado para mim neste caso. No entanto, quero expressar minha gratidão sincera pelo seu interesse.

Caso você tenha interesse em utilizar algum sistema operacional Linux, eu desenvolvi um conjunto de scripts que facilitam tarefas como a que o wxMP3val realiza. Inclusive, um dos scripts executa justamente esta tarefa (paralelamente, corrigindo vários arquivos simultaneamente de maneira rápida).

O projeto está disponível em:
https://github.com/cfgnunes/nautilus-scripts

Este projeto é mais fácil de ser mantido. Caso deseje algum script para AAC ou alguma funcionalidade específica,  só me falar que implemento para você esta funcionalidade.

Abraço!

**Comment by cfgnunes** [comment]
wxmp3gain does not support aacgain. Just mp3gain.
