### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by jyonkheel** [cfgnunes/wxmp3gain#2]
![g](https://cloud.githubusercontent.com/assets/6248760/22448432/53302c14-e794-11e6-8b2c-e551ceebbe8e.PNG)

the original mp3gain even version 1.5.2 does not support unicode characters in their filenames 
(e.g. MARETU ft. 初音ミク うまれるまえは.mp3), though this is some thing we cannot do something to fix anymore i have suggestion on how to sidestep this

1. create temp file replacing all unicode characters in file name with C supported characters
2. let mp3gain proccess that temp file
3. once processing is done apply gain to temp file
4. replace original file with temp file retaining its original unicode file name

**Comment by cfgnunes** [comment]
I'll do it.

Thanks!!

Cristiano Nunes

**Comment by cfgnunes** [comment]
Fixed on commit: 97eebae978807dafec855ef2e149e36000796360
