### ISSUE TITLE
Icons not showing up

### ISSUE THREAD

**Issue by Xeno-Idaltu** [cfgnunes/wxmp3gain#22]
OS: Kubuntu-22

I installed the deb binary and also built it from source code and on both I had errors related to the icons.

/src/gtk/bitmap.cpp(581): assert "image.IsOk()" failed in wxBitmap(): invalid image

ASSERT INFO:
../src/gtk/bitmap.cpp(581): assert "image.IsOk()" failed in wxBitmap(): invalid image

BACKTRACE:
[1] wxBitmap::wxBitmap(wxImage const&, int)
[2] wxEntry(int&, wchar_t**)
[3] __libc_start_main

**Comment by cfgnunes** [comment]
Hello! I fixed this bug in the new version.
