### ISSUE TITLE
ogggain and aacgain on Windows?

### ISSUE THREAD

**Issue by bremaya** [cfgnunes/wxmp3gain#23]
How to use ogggain and aacgain in wxmp3gain on Windows? On Linux I install it from the repository and it works perfectly (Ubuntu has a problem because of the new package in sanp, it doesn't recognize it and it doesn't work properly)

**Comment by bremaya** [comment]
?

**Comment by cfgnunes** [comment]
wxmp3gain does not support ogggain and aacgain. Just mp3gain.

**Comment by bremaya** [comment]
I solved it by creating batch scripts to use aacgain and ogggain.

**Comment by bremaya** [comment]
I solved it by creating batch scripts to use aacgain and ogggain.
