### ISSUE TITLE
Binary release for 4.2?

### ISSUE THREAD

**Issue by Skrell** [cfgnunes/wxmp3gain#27]
Super happy to see this updated!

**Comment by cfgnunes** [comment]
Hi, @Skrell ! Thanks for the issue!

I am working now on the binary releases for Windows. Coming soon, I will upload the binaries here on the GitHub!

Best regards!

**Comment by cfgnunes** [comment]
Hi, @Skrell !

Here are the binaries for Windows and Linux! 🎉
https://github.com/cfgnunes/wxmp3gain/releases/tag/4.2
